<?php
// Retrieve order
$_order = new Mage_Sales_Model_Order();
$orderId = Mage::getSingleton('checkout/session')->getLastRealOrderId();
$_order->loadByIncrementId($orderId);

// get netgiro payment url from backend(system -> configuration -> payment methods)
$redirectUrl = Mage::getStoreConfig('payment/paymentgateway/redirecturl');

// get netgiro application id for recognising merchant on netgiro from backend(system -> configuration -> payment methods)
$appID = Mage::helper('core')->decrypt(Mage::getStoreConfig('payment/paymentgateway/applicationid'));

// getsecret key for authenticating in netgiro gateway from backend(system -> configuration -> payment methods)
$secretKey = Mage::helper('core')->decrypt(Mage::getStoreConfig('payment/paymentgateway/secretkey'));

$shippingTotal =Mage::helper('paymentgateway/data')->FormatAmount($_order['shipping_incl_tax']);//Added this to get shipping including tax
$grandTotal = Mage::helper('paymentgateway/data')->FormatAmount($_order->getBaseGrandTotal()) ;

$paymentOption=$_order->getPayment()->getNetgiroPaymentType();

$signature =Mage::helper('paymentgateway/data')->GetSignature($orderId,$grandTotal);

//message which will be shown wile redirecting from magento shop to netgiro payment
$redirectNotice = Mage::getStoreConfig('payment/paymentgateway/redirectingmessage');

//Maximum number of installments the user can choose to pay with.
$maxnumberinstallments = Mage::getStoreConfig('payment/paymentgateway/maxnumberinstallments');
//Discount
$discountAmount = Mage::helper('paymentgateway/data')->FormatAmount($_order->getBaseDiscountAmount()) ;
?>

<form name="netgiropaymentform" method="post" action="<?php echo $redirectUrl; ?>">

		<input type="hidden" name="ApplicationID" value="<?php echo $appID; ?>" />
        <input type="hidden" name="Iframe" value="false" />
        <input type="hidden" name="Signature" value="<?php  echo $signature; ?>" />
        <input type="hidden" name="PaymentSuccessfulURL" value="<?php  echo Mage::getUrl('paymentgateway/payment/response', array('_secure'=>true)); ?>" />
		<input type="hidden" name="PaymentCancelledURL" value="<?php  echo Mage::getUrl('paymentgateway/payment/cancel', array('_secure'=>true)); ?>">
        <input type="hidden" name="ReturnCustomerInfo" value="true" />
		<input type="hidden" name="MaxNumberOfInstallments" value="<?php  echo $maxnumberinstallments; ?>" />
		
        <!-- Order header -->
        <input type="hidden" name="OrderId" value="<?php echo $orderId; ?>" />
        <input type="hidden" name="TotalAmount" value="<?php echo $grandTotal; ?>" />
        <input type="hidden" name="DiscountAmount" value="<?php echo $discountAmount; ?>" />
        <input type="hidden" name="ShippingAmount" value="<?php echo $shippingTotal; ?>" />
		<input type="hidden" name="PaymentOption" value="<?php echo $paymentOption; ?>" />
		
		
	<?php $i=0; foreach($_order->getAllItems() as $_product): ?>
        <?php 
                $netgiro_productprice = Mage::helper('tax')->getPrice($_product, $_product->getPrice());		
                $netgiro_productprice = Mage::helper('paymentgateway/data')->FormatAmount($netgiro_productprice);
        ?>
	<input type="hidden" name="Items[<?php echo $i ?>].ProductNo" value="<?php echo  $_product->getSku(); ?>" />
        <input type="hidden" name="Items[<?php echo $i ?>].Name" value="<?php echo  $_product->getName(); ?>" />
        <input type="hidden" name="Items[<?php echo $i ?>].Description" value="<?php echo  $_product->getDescription(); ?>" />
        <input type="hidden" name="Items[<?php echo $i ?>].UnitPrice" value="<?php echo  $netgiro_productprice; ?>" /><!-- changed this to get price incl. tax -->
        <input type="hidden" name="Items[<?php echo $i ?>].Amount" value="<?php echo  $netgiro_productprice*$_product->getQtyToInvoice(); ?>" /><!-- changed this to get price incl. tax -->
        <input type="hidden" name="Items[<?php echo $i ?>].Quantity" value="<?php echo  $_product->getQtyToInvoice()*1000; ?>" />
	<?php $i++; ?>
	<?php endforeach; ?>
</form>
<h1><?php echo $redirectNotice; ?></h1>
<script type="text/javascript">
document.netgiropaymentform.submit();
</script>