<?php
$_code = $this->getMethodCode();
$allowed_payment_options=Mage::getStoreConfig('payment/paymentgateway/netgiropaymentoptions');
$netgiro_appId=Mage::helper('core')->decrypt(Mage::getStoreConfig('payment/paymentgateway/applicationid'));
?>

<div class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
 <div class="input-box">
<?php if(substr_count($allowed_payment_options,',')>0): ?>
		<style>
        <?php /* */ ?>
        #netgiro_methods { padding: 0px; margin: 0xp; }
        #netgiro_methods li { margin: 0px; margin-bottom: -1px; background: #f3f3f3; border: solid 1px #ccc; padding: 15px; color: #676968; list-style:none; }
        #netgiro_methods li .logo { float: left; width: 150px; }
        #netgiro_methods li .logo img { border: none; box-shadow: none;}
        #netgiro_methods strong { font-size: 1.7em; font-weight: bold; }
        #netgiro_methods p { margin: 0px; }
        
        </style>
			<ul class="payment_options" id="netgiro_methods">
				 <?php $ii=0; foreach (Mage::getModel('paymentgateway/options')->toOptionArray() as $option): ?>
				   <?php if(strpos($allowed_payment_options, (string)$option["value"]) !== false): ?>
				   <?php $showPx = $showPx.'showP'.$option["value"].': true,' ?>

				   		<li class="method_reikningur" id="netgiro-branding-p<?php echo $option["value"] ?>">
				   			
                        	<input type="radio" name="PaymentOption" selected value="<?php echo $option["value"] ?>" value="false" onClick="javascript:document.getElementById('<?php echo $_code ?>_netgiro_payment_type').value='<?php echo $option["value"] ?>';" /> 
                        	<strong id="netgiro-branding-p<?php echo $option["value"] ?>-title">Netgíró reikningur</strong>
                        	<p id="netgiro-branding-p<?php echo $option["value"] ?>-text"> </p>
                        	<div class="logo" id="netgiro-branding-p<?php echo $option["value"] ?>-logo">
				   				<img id="netgiro-branding-p<?php echo $option["value"] ?>-image" src="http://developer.netgiro.is/Themes/Netgiro/logo.png" />
				   			</div>
                        	
                        </li>

					<?php $ii++; ?>
					<?php endif ?>
				<?php endforeach ?>
			</ul>
			 <input type="hidden" id="<?php echo $_code ?>_netgiro_payment_type" name="payment[netgiro_payment_type]" value="1">
<?php else: ?>
		<ul class="payment_options" id="netgiro_methods">
	    <?php $ii=0; foreach (Mage::getModel('paymentgateway/options')->toOptionArray() as $option): ?>
		   <?php if(strpos($allowed_payment_options, (string)$option["value"]) !== false): ?>
		   <?php $showPx = $showPx.'showP'.$option["value"].': true,' ?>
		   <li class="method_reikningur" id="netgiro-branding-p<?php echo $option["value"] ?>">							    	 
			 <input type="hidden" id="<?php echo $_code ?>_netgiro_payment_type" name="payment[netgiro_payment_type]" value="<?php echo $option["value"] ?>" onClick=""/>
			 <strong id="netgiro-branding-p<?php echo $option["value"] ?>-title">Netgíró reikningur</strong>
             <p id="netgiro-branding-p<?php echo $option["value"] ?>-text"> </p>
             <div class="logo" id="netgiro-branding-p<?php echo $option["value"] ?>-logo">
				<img id="netgiro-branding-p<?php echo $option["value"] ?>-image" src="http://developer.netgiro.is/Themes/Netgiro/logo.png" />
			 </div>
		   </li>
		   <?php endif ?>
        <?php endforeach ?>
		</ul>
<?php endif ?>
	</div>	
</div>
<script src="//api.netgiro.is/scripts/netgiro.api.js" type="text/javascript"></script>

<script>
  jQuery(document).ready(function () {
      netgiro.branding.options = { <?php echo $showPx ?> } 
      netgiro.branding.init("<?php echo $netgiro_appId ?>");
  });
</script>

<script>
jQuery(function() {
    jQuery('.method_reikningur').click(function() {
      jQuery(this).find('input').prop('checked', true);
    });
});
</script>




